CUDA_VISIBLE_DEVICES=2 python -m deepcompressor.app.diffusion.ptq configs/model/flux.1-schnell.yaml configs/int4.yaml --save-model true
CUDA_VISIBLE_DEVICES=2 python -m deepcompressor.app.diffusion.ptq configs/model/flux.1-schnell.yaml configs/quartz/int4.yaml --save-model true
CUDA_VISIBLE_DEVICES=2 python -m deepcompressor.app.diffusion.ptq configs/model/flux.1-schnell.yaml configs/quartz/int4.yaml configs/gptq.yaml --save-model true
CUDA_VISIBLE_DEVICES=2 python -m deepcompressor.app.diffusion.ptq configs/model/flux.1-schnell.yaml configs/quartz/int4.yaml configs/reverse_smooth.yaml --save-model true
CUDA_VISIBLE_DEVICES=2 python -m deepcompressor.app.diffusion.ptq configs/model/flux.1-schnell.yaml configs/quartz/int4.yaml configs/gptq.yaml configs/reverse_smooth.yaml --save-model true
CUDA_VISIBLE_DEVICES=2 python -m deepcompressor.app.diffusion.ptq configs/model/flux.1-schnell.yaml configs/mxfp4.yaml --save-model true
CUDA_VISIBLE_DEVICES=2 python -m deepcompressor.app.diffusion.ptq configs/model/flux.1-schnell.yaml configs/mxfp4.yaml configs/gptq.yaml --save-model true
CUDA_VISIBLE_DEVICES=2 python -m deepcompressor.app.diffusion.ptq configs/model/flux.1-schnell.yaml configs/mxfp4.yaml configs/smooth.yaml --save-model true
CUDA_VISIBLE_DEVICES=2 python -m deepcompressor.app.diffusion.ptq configs/model/flux.1-schnell.yaml configs/mxfp4.yaml configs/reverse_smooth.yaml --save-model true
CUDA_VISIBLE_DEVICES=2 python -m deepcompressor.app.diffusion.ptq configs/model/flux.1-schnell.yaml configs/nvfp4.yaml --save-model true
CUDA_VISIBLE_DEVICES=2 python -m deepcompressor.app.diffusion.ptq configs/model/flux.1-schnell.yaml configs/nvfp4.yaml configs/gptq.yaml --save-model true
CUDA_VISIBLE_DEVICES=2 python -m deepcompressor.app.diffusion.ptq configs/model/flux.1-schnell.yaml configs/nvfp4.yaml configs/smooth.yaml --save-model true
CUDA_VISIBLE_DEVICES=2 python -m deepcompressor.app.diffusion.ptq configs/model/flux.1-schnell.yaml configs/nvfp4.yaml configs/reverse_smooth.yaml --save-model true
